import json
import os
import requests
import numpy as np
import nibabel as nib
from nilearn import datasets

OUTPUT_DIR   = "data/brain_regions"
ANNOT_DIR    = os.path.expanduser("~/nilearn_data/fsaverage_annot")
HEMISPHERES  = ["lh", "rh"]

ANNOT_URLS = {
    "lh": "https://raw.githubusercontent.com/nilearn/nilearn/main/nilearn/data/fsaverage/lh.aparc.annot",
    "rh": "https://raw.githubusercontent.com/nilearn/nilearn/main/nilearn/data/fsaverage/rh.aparc.annot",
}

PARKINSONS_RELEVANT = {
    "precentral",
    "postcentral",
    "superiorfrontal", "rostralmiddlefrontal",
    "isthmuscingulate", "posteriorcingulate",
    "entorhinal", "parahippocampal",
    "insula",
    "superiortemporal", "middletemporal",
    "inferiorparietal", "supramarginal",
}

def download_fsaverage():
    """
    Download the fsaverage surface dataset from Nilearn.
    """
    return datasets.fetch_surf_fsaverage("fsaverage")

def download_annotations():
    """
    Fetch cortical annotation files for left and right hemispheres.
    """
    os.makedirs(ANNOT_DIR, exist_ok=True)
    annot_paths = {}

    for hemi, url in ANNOT_URLS.items():
        out_path = os.path.join(ANNOT_DIR, f"{hemi}.aparc.annot")
        if os.path.exists(out_path):
            annot_paths[hemi] = out_path
            continue

        try:
            res = requests.get(url, timeout=30)
            if res.status_code == 200:
                with open(out_path, "wb") as f:
                    f.write(res.content)
                annot_paths[hemi] = out_path
                continue
        except requests.RequestException:
            pass

        destrieux = datasets.fetch_atlas_surf_destrieux()

        raise FileNotFoundError(
            f"Could not download {hemi}.aparc.annot.\n"
            f"Please manually download from {url} and place it in {out_path}"
        )

    return annot_paths


def load_gifti_surface(gifti_path: str):
    """
    Load and extract coordinate and face arrays from a GIFTI surface file.
    """
    img = nib.load(gifti_path)
    coords = img.darrays[0].data.astype(np.float32)
    faces  = img.darrays[1].data.astype(np.int32)
    return coords, faces


def write_obj(filepath: str, vertices: np.ndarray, faces: np.ndarray):
    """
    Write 3D mesh vertices and faces to a standard Wavefront OBJ file.
    """
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w") as f:
        f.write(f"# Generated by brain_split.py\n")
        f.write(f"# Vertices: {len(vertices)}  Faces: {len(faces)}\n\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")


def extract_regions(hemi: str, fsaverage, annot_paths: dict) -> list:
    """
    Split the hemisphere mesh into individual brain regions and export to OBJ.
    """
    hemi_long = "left" if hemi == "lh" else "right"
    surf_path = fsaverage[f"pial_{hemi_long}"]
    annot_path = annot_paths[hemi]

    coords, faces = load_gifti_surface(surf_path)
    labels, ctab, region_names = nib.freesurfer.read_annot(annot_path)

    region_names = [
        r.decode("utf-8") if isinstance(r, bytes) else r
        for r in region_names
    ]

    region_info_list = []

    for region_idx, region_name in enumerate(region_names):
        if region_name in ("unknown", "corpuscallosum", "???"):
            continue 

        vertex_mask = labels == region_idx
        vertex_indices = np.where(vertex_mask)[0]

        if len(vertex_indices) < 10:
            continue

        face_mask = np.all(vertex_mask[faces], axis=1)
        region_faces_global = faces[face_mask]

        if len(region_faces_global) == 0:
            continue

        unique_verts, inverse = np.unique(region_faces_global, return_inverse=True)
        local_faces    = inverse.reshape(-1, 3)
        local_vertices = coords[unique_verts]

        safe_name = region_name.lower().replace("-", "_").replace(" ", "_")
        filename  = f"{hemi}_{safe_name}.obj"
        filepath  = os.path.join(OUTPUT_DIR, filename)
        write_obj(filepath, local_vertices, local_faces)

        is_parkinsons = region_name.lower() in PARKINSONS_RELEVANT

        region_info_list.append({
            "id":               f"{hemi}_{safe_name}",
            "hemisphere":       hemi,
            "region_name":      region_name,
            "file":             filename,
            "vertex_count":     int(len(unique_verts)),
            "face_count":       int(len(local_faces)),
            "parkinsons_relevant": is_parkinsons,
            "source":           "cortical"
        })

    return region_info_list


def write_mapping(all_regions: list):
    """
    Save or update the structural regions mapping details in a JSON file.
    """
    out_path = os.path.join(OUTPUT_DIR, "mapping.json")
    
    if os.path.exists(out_path):
        with open(out_path, "r", encoding="utf-8") as f:
            mapping = json.load(f)
    else:
        mapping = {}

    for r in all_regions:
        mapping[r["id"]] = {
            "hemisphere":          r["hemisphere"],
            "region_name":         r["region_name"],
            "file":                r["file"],
            "vertex_count":        r["vertex_count"],
            "face_count":          r["face_count"],
            "parkinsons_relevant": r["parkinsons_relevant"],
            "source":              r["source"],
            "metabolites":         [],
        }

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(mapping, f, indent=2, ensure_ascii=False)

    return out_path


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    fsaverage   = download_fsaverage()
    annot_paths = download_annotations()
    all_regions = []

    for hemi in HEMISPHERES:
        regions = extract_regions(hemi, fsaverage, annot_paths)
        all_regions.extend(regions)

    mapping_path = write_mapping(all_regions)