"""
brain_split.py  —  Split fsaverage brain into per-region OBJ files
===================================================================
Uses the Desikan-Killiany atlas (aparc) to split both hemispheres
of the fsaverage surface into individually named .obj files, ready
to import into Blender or load directly in React Three Fiber.

Output structure:
  data/brain_regions/
    lh_superiorfrontal.obj
    lh_precentral.obj
    ...  (34 regions × 2 hemispheres = 68 files)
    mapping.json

Dependencies:
    uv pip install nilearn nibabel numpy requests
"""

import json
import os
import requests
import numpy as np

try:
    import nibabel as nib
    from nilearn import datasets
except ImportError:
    raise SystemExit("Run: uv pip install nilearn nibabel numpy requests")

# ── Config ────────────────────────────────────────────────────────────────────

OUTPUT_DIR   = "data/brain_regions"
ANNOT_DIR    = os.path.expanduser("~/nilearn_data/fsaverage_annot")
HEMISPHERES  = ["lh", "rh"]

# Annotation files hosted on GitHub (FreeSurfer's fsaverage label files)
ANNOT_URLS = {
    "lh": "https://raw.githubusercontent.com/nilearn/nilearn/main/nilearn/data/fsaverage/lh.aparc.annot",
    "rh": "https://raw.githubusercontent.com/nilearn/nilearn/main/nilearn/data/fsaverage/rh.aparc.annot",
}

PARKINSONS_RELEVANT = {
    "caudate", "putamen", "pallidum",
    "precentral",
    "postcentral",
    "superiorfrontal", "rostralmiddlefrontal",
    "isthmuscingulate", "posteriorcingulate",
    "hippocampus", "entorhinal", "parahippocampal",
    "insula",
    "superiortemporal", "middletemporal",
    "inferiorparietal", "supramarginal",
}

# ── Download helpers ──────────────────────────────────────────────────────────

def download_fsaverage():
    print("Loading fsaverage GIFTI surfaces via nilearn...")
    fs = datasets.fetch_surf_fsaverage("fsaverage")
    print("Surfaces ready.")
    return fs


def download_annotations():
    """
    Download lh/rh .aparc.annot files from nilearn's GitHub repo.
    These contain the Desikan-Killiany region labels per vertex.
    """
    os.makedirs(ANNOT_DIR, exist_ok=True)
    annot_paths = {}

    for hemi, url in ANNOT_URLS.items():
        out_path = os.path.join(ANNOT_DIR, f"{hemi}.aparc.annot")
        if os.path.exists(out_path):
            print(f"  Annotation already cached: {out_path}")
            annot_paths[hemi] = out_path
            continue

        print(f"  Downloading {hemi}.aparc.annot ...")
        res = requests.get(url, timeout=30)
        if res.status_code != 200:
            # Fallback: use nilearn's built-in fetcher
            print(f"  GitHub fetch failed ({res.status_code}), trying nilearn fetcher...")
            fs5 = datasets.fetch_surf_fsaverage("fsaverage5")
            # fsaverage5 annot files are in the same format
            # Copy from nilearn's cache if present
            nilearn_annot = os.path.join(
                os.path.expanduser("~/nilearn_data"),
                "fsaverage5", f"{hemi}.aparc.annot"
            )
            if os.path.exists(nilearn_annot):
                import shutil
                shutil.copy(nilearn_annot, out_path)
            else:
                raise FileNotFoundError(
                    f"Could not download {hemi}.aparc.annot.\n"
                    f"Please manually download from:\n"
                    f"https://github.com/nilearn/nilearn/tree/main/nilearn/data/fsaverage"
                )
        else:
            with open(out_path, "wb") as f:
                f.write(res.content)
            print(f"  Saved → {out_path}")

        annot_paths[hemi] = out_path

    return annot_paths


def load_gifti_surface(gifti_path: str):
    """
    Load a .gii or .gii.gz surface file.
    Returns (coords, faces) as numpy arrays.
    """
    img = nib.load(gifti_path)
    # GIFTI surfaces have two DataArrays: coords (float) and faces (int)
    coords = img.darrays[0].data.astype(np.float32)
    faces  = img.darrays[1].data.astype(np.int32)
    return coords, faces


# ── OBJ export ────────────────────────────────────────────────────────────────

def write_obj(filepath: str, vertices: np.ndarray, faces: np.ndarray):
    """
    Write a minimal Wavefront OBJ file.
    vertices: (N, 3) float array
    faces:    (M, 3) int array  (0-indexed, will be written as 1-indexed)
    """
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w") as f:
        f.write(f"# Generated by brain_split.py\n")
        f.write(f"# Vertices: {len(vertices)}  Faces: {len(faces)}\n\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")
        for face in faces:
            # OBJ is 1-indexed
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")


# ── Region extraction ─────────────────────────────────────────────────────────

def extract_regions(hemi: str, fsaverage, annot_paths: dict) -> list:
    """
    For one hemisphere, load the pial GIFTI surface and annotation,
    extract each region as a sub-mesh and write it to an OBJ file.
    """
    print(f"\n── Processing {hemi} hemisphere ──")

    hemi_long = "left" if hemi == "lh" else "right"
    surf_path = fsaverage[f"pial_{hemi_long}"]
    annot_path = annot_paths[hemi]

    print(f"  Surface:    {surf_path}")
    print(f"  Annotation: {annot_path}")

    coords, faces = load_gifti_surface(surf_path)
    labels, ctab, region_names = nib.freesurfer.read_annot(annot_path)

    # Decode bytes to str if needed
    region_names = [
        r.decode("utf-8") if isinstance(r, bytes) else r
        for r in region_names
    ]

    print(f"  {len(region_names)} regions, {len(coords)} vertices, {len(faces)} faces")

    # region_names is a list of bytes — decode to str
    region_names = [r.decode("utf-8") if isinstance(r, bytes) else r
                    for r in region_names]

    print(f"  Found {len(region_names)} regions, {len(coords)} vertices")

    region_info_list = []

    for region_idx, region_name in enumerate(region_names):
        if region_name in ("unknown", "corpuscallosum", "???"):
            continue  # skip non-cortical labels

        # Find all vertices belonging to this region
        vertex_mask = labels == region_idx
        vertex_indices = np.where(vertex_mask)[0]

        if len(vertex_indices) < 10:
            continue  # skip degenerate regions

        # Find all faces where ALL 3 vertices are in this region
        face_mask = np.all(vertex_mask[faces], axis=1)
        region_faces_global = faces[face_mask]

        if len(region_faces_global) == 0:
            print(f"  ⚠ No faces for {hemi}_{region_name}, skipping")
            continue

        # Re-index: map global vertex indices to local (0-based) indices
        unique_verts, inverse = np.unique(region_faces_global, return_inverse=True)
        local_faces    = inverse.reshape(-1, 3)
        local_vertices = coords[unique_verts]

        # Write OBJ
        safe_name = region_name.lower().replace("-", "_").replace(" ", "_")
        filename  = f"{hemi}_{safe_name}.obj"
        filepath  = os.path.join(OUTPUT_DIR, filename)
        write_obj(filepath, local_vertices, local_faces)

        is_parkinsons = region_name.lower() in PARKINSONS_RELEVANT

        region_info_list.append({
            "id":               f"{hemi}_{safe_name}",
            "hemisphere":       hemi,
            "region_name":      region_name,
            "file":             filename,
            "vertex_count":     int(len(unique_verts)),
            "face_count":       int(len(local_faces)),
            "parkinsons_relevant": is_parkinsons,
        })

        marker = "★" if is_parkinsons else " "
        print(f"  {marker} {hemi}_{region_name:<30} "
              f"{len(unique_verts):>6} verts  {len(local_faces):>6} faces  → {filename}")

    return region_info_list


# ── mapping.json ──────────────────────────────────────────────────────────────

def write_mapping(all_regions: list):
    """
    Write mapping.json — used by your React frontend to link
    region mesh names to metadata, and by your RAG system to
    link metabolites to brain regions.

    Structure:
    {
      "lh_precentral": {
        "hemisphere": "lh",
        "region_name": "precentral",
        "file": "lh_precentral.obj",
        "parkinsons_relevant": true,
        "metabolites": []          ← filled later by your RAG pipeline
      },
      ...
    }
    """
    mapping = {}
    for r in all_regions:
        mapping[r["id"]] = {
            "hemisphere":          r["hemisphere"],
            "region_name":         r["region_name"],
            "file":                r["file"],
            "vertex_count":        r["vertex_count"],
            "face_count":          r["face_count"],
            "parkinsons_relevant": r["parkinsons_relevant"],
            "metabolites":         [],   # populated later by RAG extraction
        }

    out_path = os.path.join(OUTPUT_DIR, "mapping.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(mapping, f, indent=2, ensure_ascii=False)

    print(f"\n mapping.json saved → {out_path}")
    return out_path


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    fsaverage   = download_fsaverage()
    annot_paths = download_annotations()
    all_regions = []

    for hemi in HEMISPHERES:
        regions = extract_regions(hemi, fsaverage, annot_paths)
        all_regions.extend(regions)

    mapping_path = write_mapping(all_regions)

    # Summary
    total      = len(all_regions)
    parkinsons = sum(1 for r in all_regions if r["parkinsons_relevant"])
    print(f"\n{'─'*55}")
    print(f"Done.  {total} region OBJ files written to {OUTPUT_DIR}/")
    print(f"       {parkinsons} regions flagged as Parkinson's-relevant (★)")
    print(f"       mapping.json ready for React + RAG pipeline")
    print(f"{'─'*55}")
    print(f"\nNext steps:")
    print(f"  1. Import OBJ files into Blender and export as a single .glb")
    print(f"     (each region will be a named mesh object)")
    print(f"  2. Load the .glb in React Three Fiber")
    print(f"  3. Use mapping.json to highlight regions by metabolite")